version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-pip:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: pip
      - run:
          command: |
              pip install -r requirements.txt
              pip install coverage coveralls
              pip install dtaidistance
      - python/save-cache:
          key: pip
      - run: pip install -e -v .
      - run:
          command: |
              coverage run -m unittest discover tests
              coveralls

workflows:
  main:
    jobs:
      - build-pip
